import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import worker from '../server/worker';
import {STAGES,stageTeam,elapsedRemaining,newRound,opponentPrompt} from '../shared/round';
import {LESSONS} from '../shared/courses';
class Database {db=new DatabaseSync(':memory:');constructor(){this.db.exec(fs.readFileSync('drizzle/0000_bitter_synch.sql','utf8'))}prepare(sql:string){const db=this.db;let args:any[]=[];const statement={bind(...values:any[]){args=values;return statement},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}};return statement}async batch(items:any[]){this.db.exec('BEGIN');try{const results=[];for(const i of items)results.push(await i.run());this.db.exec('COMMIT');return results}catch(e){this.db.exec('ROLLBACK');throw e}}}
function setup(){const DB=new Database();const env:any={DB,ADMIN_EMAILS:'editor@example.com',ASSETS:{fetch:()=>new Response('assets')}};async function call(path:string,method='GET',data?:unknown,user='alice',email='alice@example.com',origin='https://skb.test'){const headers:any={'oai-authenticated-user-id':user,'oai-authenticated-user-email':email};if(method!=='GET'){headers['content-type']='application/json';headers.origin=origin}if(!user){delete headers['oai-authenticated-user-id'];delete headers['oai-authenticated-user-email']}const r=await worker.fetch(new Request('https://skb.test/api'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),env);return {status:r.status,data:await r.json() as any}}return {call}}
test('PF speaking order is independent from side and deadlines survive timer delays',()=>{assert.equal(STAGES.length,11);assert.equal(STAGES.reduce((sum,s)=>sum+s.seconds,0),2100);assert.equal(stageTeam(STAGES[0],'CON'),'CON');assert.equal(stageTeam(STAGES[1],'CON'),'PRO');assert.equal(stageTeam(STAGES[2],'CON'),'BOTH');assert.equal(elapsedRemaining(10000,3456),7);assert.equal(elapsedRemaining(10000,15000),0);const round=newRound({resolution:'Custom resolution',scenario:'custom',side:'CON',first:'PRO',mode:'partner'});assert.equal(round.prep.CON,180);assert.match(opponentPrompt(round),/Custom resolution/)});
test('saved work is private, versioned, and cannot be overwritten by another user',async()=>{const {call}=setup(),id=crypto.randomUUID();const doc={id,kind:'case',title:'First case',data:{framework:'my reasoning'},version:0};assert.equal((await call('/documents','PUT',doc,'')).status,401);assert.equal((await call('/documents','PUT',doc)).status,200);assert.deepEqual((await call('/documents','GET',undefined,'bob')).data,[]);assert.equal((await call('/documents','PUT',doc,'bob')).status,404);assert.equal((await call('/documents','PUT',doc)).status,409);assert.equal((await call('/documents','PUT',{...doc,version:1,title:'Revised'})).data.version,2);assert.equal((await call('/documents','PUT',{...doc,version:2},'alice','alice@example.com','https://attacker.test')).status,403);assert.equal((await call('/documents/'+id,'DELETE',{},'bob')).status,200);assert.equal((await call('/documents')).data.length,1)});
test('community contributions require review and editors can unpublish them',async()=>{const {call}=setup();const input={title:'A teaching guide',format:'Public Forum',kind:'Guide',description:'Practice careful reasoning.',body:'A useful original guide with enough content.',url:'',rights:true};assert.equal((await call('/submissions','POST',{...input,url:'javascript:alert(1)'})).status,400);const created=await call('/submissions','POST',input);assert.equal(created.status,201);assert.equal((await call('/catalog')).data.resources.length,10);assert.equal((await call('/admin')).status,403);assert.equal((await call('/admin/review','POST',{id:created.data.id,status:'approved'},'editor','editor@example.com')).status,200);assert.equal((await call('/catalog')).data.resources.length,11);assert.equal((await call('/reports','POST',{resourceId:created.data.id,reason:'Please check attribution.'},'bob')).status,200);assert.equal((await call('/admin/review','POST',{id:created.data.id,status:'pending'},'editor','editor@example.com')).status,200);assert.equal((await call('/catalog')).data.resources.length,10)});
test('lesson progress validates the answer and account deletion preserves another learner’s data',async()=>{const {call}=setup(),lesson=LESSONS[0];assert.equal((await call('/progress','POST',{lessonId:lesson.id,answer:2})).status,400);assert.deepEqual((await call('/progress')).data,[]);assert.equal((await call('/progress','POST',{lessonId:lesson.id,answer:lesson.correct})).status,200);const d={id:crypto.randomUUID(),kind:'round',title:'Bob round',data:{notes:'private'},version:0};await call('/documents','PUT',d,'bob');await call('/profile','PUT',{name:'Alice',role:'teacher',bio:'Learning together.'});assert.equal((await call('/account')).data.progress.length,1);assert.equal((await call('/account','DELETE',{})).status,200);assert.deepEqual((await call('/progress')).data,[]);assert.equal((await call('/documents','GET',undefined,'bob')).data.length,1)});
