import React from 'react';

export const journeyPrompts = {
  baseline: 'A school notices that students who attend an optional study group earn higher grades. A speaker concludes that requiring every student to attend will improve grades. What assumption would you question, and why?',
  transfer: 'A town observes that residents who cycle to work report higher well-being. A speaker concludes that subsidizing bicycles will improve well-being across the town. What assumption would you question? Explain what evidence could change your view.',
};
export const reviewCriteria = [
  'I describe the argument fairly before objecting.',
  'I identify a specific assumption connecting the observation to the conclusion.',
  'I explain why that assumption needs support without inventing evidence.',
  'I say what evidence or clarification could change my view.',
];
export type JourneyRecord = {baseline:string; baselineSubmitted:boolean; transfer:string; transferSubmitted:boolean; reflection:string; checks:string[]};
export const emptyJourney:JourneyRecord = {baseline:'',baselineSubmitted:false,transfer:'',transferSubmitted:false,reflection:'',checks:[]};
type Props = {record:JourneyRecord; update:(value:JourneyRecord)=>void; start:()=>void};
export function LearnHome({record,update,start}:Props){
  return <section className="journey-home" aria-labelledby="welcome-title">
    <p className="kicker">THE REASONING STUDIO · LESSON 01</p>
    <h1 id="welcome-title">Make room for a better argument.</h1>
    <p className="journey-lead">Learn to find an unstated assumption, respond fairly, and revise your reasoning.</p>
    <ol className="journey-steps"><li>Try an argument</li><li>Explore the lesson</li><li>Practice & revise</li><li>Apply it somewhere new</li></ol>
    <div className="journey-grid"><article className="exercise"><p className="kicker">BEFORE THE LESSON</p><h2>Where would you begin?</h2><p>Try this before viewing the explanation. There is no score; we will keep your first attempt for comparison.</p><blockquote>{journeyPrompts.baseline}</blockquote><p className="small-note">Fictional practice scenario. No research finding is being asserted.</p><label htmlFor="baseline">Your starting response</label><textarea id="baseline" maxLength={5000} readOnly={record.baselineSubmitted} value={record.baseline} onChange={e=>update({...record,baseline:e.target.value})}/>{record.baselineSubmitted?<><p role="status">First attempt recorded for this session.</p><button className="primary" onClick={start}>Continue to lesson</button></>:<><button className="primary" disabled={!record.baseline.trim()} onClick={()=>{update({...record,baselineSubmitted:true});start();}}>Record first attempt & start</button><button className="text-button" onClick={start}>Explore lesson without an initial attempt</button></>}</article>
    <aside className="journey-note"><p className="kicker">WHAT YOU WILL PRACTICE</p><h2>Challenge the connection.</h2><p>A true observation can still lead to a conclusion that needs more support. We will use a school phone-policy example to examine that gap.</p><ul><li>Three short visual chapters</li><li>Prepared explanations and optional AI questions</li><li>A rebuttal you can revise</li><li>A new argument to test your understanding</li></ul><p className="disclosure">Teaching draft · AI-assisted content awaiting educator review. Your work stays in this tab; reloading clears it. Download your record before leaving.</p></aside></div>
  </section>;
}
export function ProgressReview({record,update,initial,revision,onDownload}:{record:JourneyRecord;update:Props['update'];initial:string;revision:string;onDownload:()=>void}){
  return <section aria-labelledby="progress-title"><p className="kicker">MY PROGRESS · THIS SESSION</p><h1 id="progress-title">Notice how your reasoning changes.</h1><p>These are your own attempts, not an AI score or a certificate. Different examples let you examine whether a skill transfers.</p><div className="journey-grid"><article className="exercise"><h2>A fresh argument</h2><blockquote>{journeyPrompts.transfer}</blockquote><p className="small-note">Fictional practice scenario. Try it independently before opening the review prompts.</p><label htmlFor="transfer">Your response to the new argument</label><textarea id="transfer" maxLength={5000} readOnly={record.transferSubmitted} value={record.transfer} onChange={e=>update({...record,transfer:e.target.value})}/>{!record.transferSubmitted?<button className="primary" disabled={!record.transfer.trim()} onClick={()=>update({...record,transferSubmitted:true})}>Record attempt & review</button>:<div><h3>Review your reasoning</h3><p>One possible concern is that people who already feel healthier may be more likely to cycle. A subsidy also may not change everyone’s travel behavior. These are questions to investigate, not proof that the policy fails. Other justified readings are possible.</p><fieldset><legend>Self-review: which statements describe your response?</legend>{reviewCriteria.map(criterion=><label className="review-check" key={criterion}><input type="checkbox" checked={record.checks.includes(criterion)} onChange={e=>update({...record,checks:e.target.checked?[...record.checks,criterion]:record.checks.filter(c=>c!==criterion)})}/>{criterion}</label>)}</fieldset><label htmlFor="reflection">What changed in your approach?</label><textarea id="reflection" maxLength={5000} value={record.reflection} onChange={e=>update({...record,reflection:e.target.value})} placeholder="What would you do differently next time? What remains uncertain?"/></div>}</article><aside className="exercise"><h2>Your learning record</h2>{[{title:'Starting attempt',text:record.baselineSubmitted?record.baseline:''},{title:'Lesson response',text:initial},{title:'Revised rebuttal',text:revision}].map(item=><section className="record-entry" key={item.title}><h3>{item.title}</h3><p>{item.text||'No response recorded yet.'}</p></section>)}<button className="primary" onClick={onDownload}>Download learning record</button><p className="small-note">Includes prompts, responses, lesson version, and self-review. Stored only in this tab until you download it. Downloading does not save it to an account.</p></aside></div></section>;
}
