import {z} from 'zod';
import {useEffect,useRef,useState} from 'react';
import {lesson} from '../shared/teaching';
import {tutorReplySchema,type ArgumentMap,type TutorReply} from '../shared/tutor';
export default function LiveTutor({chapter,map,onReply,onPause}:{chapter:number;map:ArgumentMap;onReply:(reply:TutorReply)=>void;onPause:()=>void}){
  const [available,setAvailable]=useState(false),[status,setStatus]=useState('Checking tutor connection…');
  const [question,setQuestion]=useState(''),[reply,setReply]=useState<TutorReply|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [history,setHistory]=useState<{role:'user'|'assistant';content:string}[]>([]);
  const controller=useRef<AbortController|null>(null);
  useEffect(()=>{const c=new AbortController();fetch('/api/tutor',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(raw=>{const data=z.object({available:z.boolean(),reason:z.string().nullable().optional()}).parse(raw);setAvailable(data.available===true);setStatus(data.available?'Connected to DeepSeek':data.reason||'Live tutor is not configured.');}).catch(()=>{if(!c.signal.aborted)setStatus('Live tutor server is unavailable. Prepared questions still work.');});return()=>{c.abort();controller.current?.abort();};},[]);
  async function ask(){if(busy||!available||!question.trim())return;onPause();setBusy(true);setError('');const c=new AbortController();controller.current=c;
    try{const response=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({lessonId:lesson.id,lessonVersion:lesson.version,chapter,question,map,history})});const raw=await response.json();if(!response.ok){const error=z.object({error:z.string()}).safeParse(raw);throw Error(error.success?error.data.error:'Tutor unavailable.');}const data=z.object({reply:tutorReplySchema,elapsedMs:z.number().nonnegative()}).parse(raw);const answer=data.reply;if(c.signal.aborted)return;setReply(answer);onReply(answer);setHistory(h=>[...h,{role:'user' as const,content:question},{role:'assistant' as const,content:answer.explanation+'\n'+answer.followUp}].slice(-6));setQuestion('');setStatus(`DeepSeek response · ${(data.elapsedMs/1000).toFixed(1)}s · AI interpretation, not a verified judgment`);
    }catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Unable to get a response.');}finally{if(controller.current===c){setBusy(false);controller.current=null;}}
  }
  return <section className="live-tutor" aria-label="Live tutor"><p className="kicker">GENERATIVE EXPERIMENT</p><h2>Ask about this argument.</h2><p className="small-note" role="status">{status}</p><p className="small-note">On submit, your question, current map, chapter, and up to three previous exchanges are sent to DeepSeek. Your exercise writing is not sent. Conversation stays in this tab; changing chapters clears it.</p><form onSubmit={e=>{e.preventDefault();void ask();}}><label>Your question or correction<textarea maxLength={1200} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What if the restriction only applies during class?" disabled={busy}/></label><button className="primary" disabled={!available||busy||!question.trim()}>{busy?'Thinking…':'Ask tutor'}</button>{busy&&<button type="button" onClick={()=>{controller.current?.abort();controller.current=null;setBusy(false);setError('Request cancelled. Your question is still here.');}}>Cancel</button>}</form>{error&&<p role="alert">{error}</p>}{reply&&<div className="generated-answer" aria-live="polite"><strong>AI-generated explanation</strong><p>{reply.explanation}</p><strong>Try this next</strong><p>{reply.followUp}</p><p className="small-note">The map now shows the proposed interpretation. Correct it in your next question, or replay a chapter to restore the authored map.</p></div>}</section>;
}
