import {z} from 'zod';
import {LESSONS} from '../shared/courses';
import {RESOURCES} from '../shared/resources';
type Env={DB:D1Database;ASSETS:Fetcher;ADMIN_EMAILS?:string;LOCAL_DEV?:string};
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const str=(max:number)=>z.string().trim().min(1).max(max);
const docSchema=z.object({id:z.string().uuid(),kind:z.enum(['round','case','speech']),title:str(500),data:z.record(z.string(),z.unknown()),version:z.number().int().nonnegative()});
const submissionSchema=z.object({title:str(160),format:str(50),kind:z.enum(['Guide','Template','Video','External resource','Teaching plan']),description:str(500),url:z.union([z.literal(''),z.url().refine(v=>new URL(v).protocol==='https:','Use an https link')]),body:z.string().trim().max(20000),rights:z.literal(true)}).refine(v=>v.body.length>20||v.url.length>0,{message:'Add a link or at least 20 characters of resource content.'});
function identity(request:Request,env:Env){const url=new URL(request.url);const local=env.LOCAL_DEV==='true'&&['127.0.0.1','localhost'].includes(url.hostname);const id=local?'local-founder':request.headers.get('oai-authenticated-user-id');if(!id)return null;const email=local?'local@skb.test':request.headers.get('oai-authenticated-user-email')||'';let name=request.headers.get('oai-authenticated-user-full-name')||'';if(request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'){try{name=decodeURIComponent(name)}catch{name=''}}return {id,email,name:name||'SKB learner',admin:local||(env.ADMIN_EMAILS||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean).includes(email.toLowerCase())}}
async function body(req:Request){if(Number(req.headers.get('content-length')||0)>200000)throw new Error('Payload too large');const s=await req.text();if(s.length>200000)throw new Error('Payload too large');return JSON.parse(s)}
async function api(request:Request,env:Env){const url=new URL(request.url),path=url.pathname,method=request.method,user=identity(request,env);if(method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==url.origin)return json({error:'Cross-origin writes are not allowed.'},403);if(request.headers.get('sec-fetch-site')==='cross-site')return json({error:'Cross-site writes are not allowed.'},403);if(!request.headers.get('content-type')?.startsWith('application/json'))return json({error:'Use a JSON request.'},415)}
if(path==='/api/health')return json({ok:true,version:'0.1.0'});
if(path==='/api/me'&&method==='GET'){let profile=null;if(user)profile=await env.DB.prepare('SELECT name,role,bio FROM profiles WHERE id=?').bind(user.id).first();return json({user:user?{...user,...profile}:null,aiCoach:false})}
if(path==='/api/catalog'&&method==='GET'){const rows=await env.DB.prepare("SELECT id,author,title,format,kind,description,url,body,created_at FROM submissions WHERE status='approved' ORDER BY created_at DESC LIMIT 200").all();return json({lessons:LESSONS,resources:[...RESOURCES.map(x=>({...x,author:'SKB editorial',official:true})),...rows.results]})}
if(!user)return json({error:'Sign in to save your work or contribute.'},401);
if(path==='/api/account'&&method==='GET'){const [profile,documents,progress,submissions]=await Promise.all([env.DB.prepare('SELECT * FROM profiles WHERE id=?').bind(user.id).first(),env.DB.prepare('SELECT id,kind,title,data,version,updated_at FROM documents WHERE owner_id=?').bind(user.id).all<any>(),env.DB.prepare('SELECT lesson_id,completed_at FROM progress WHERE owner_id=?').bind(user.id).all(),env.DB.prepare('SELECT * FROM submissions WHERE owner_id=?').bind(user.id).all()]);return json({exportedAt:new Date().toISOString(),profile,documents:documents.results.map(d=>({...d,data:JSON.parse(d.data)})),progress:progress.results,submissions:submissions.results})}
if(path==='/api/account'&&method==='DELETE'){await env.DB.batch([env.DB.prepare('DELETE FROM reports WHERE owner_id=? OR resource_id IN (SELECT id FROM submissions WHERE owner_id=?)').bind(user.id,user.id),env.DB.prepare('DELETE FROM submissions WHERE owner_id=?').bind(user.id),env.DB.prepare('DELETE FROM documents WHERE owner_id=?').bind(user.id),env.DB.prepare('DELETE FROM progress WHERE owner_id=?').bind(user.id),env.DB.prepare('DELETE FROM profiles WHERE id=?').bind(user.id)]);return json({ok:true})}
if(path==='/api/profile'&&method==='PUT'){const v=z.object({name:str(60),role:z.enum(['learner','competitor','judge','teacher']),bio:z.string().trim().max(500)}).parse(await body(request));await env.DB.prepare('INSERT INTO profiles (id,name,role,bio,created_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role=excluded.role,bio=excluded.bio').bind(user.id,v.name,v.role,v.bio,new Date().toISOString()).run();return json({ok:true})}
if(path==='/api/documents'&&method==='GET'){const rows=await env.DB.prepare('SELECT id,kind,title,data,version,updated_at FROM documents WHERE owner_id=? ORDER BY updated_at DESC LIMIT 100').bind(user.id).all<any>();return json(rows.results.map(r=>({...r,data:JSON.parse(r.data)})))}
if(path==='/api/documents'&&method==='PUT'){const v=docSchema.parse(await body(request));const data=JSON.stringify(v.data);if(data.length>160000)return json({error:'This document is too large to save.'},413);const previous=await env.DB.prepare('SELECT owner_id,version FROM documents WHERE id=?').bind(v.id).first<{owner_id:string;version:number}>();if(previous&&previous.owner_id!==user.id)return json({error:'Document not found.'},404);if(previous&&previous.version!==v.version)return json({error:'A newer version exists. Reload your saved work before editing again.'},409);const next=(previous?.version||0)+1;const now=new Date().toISOString();if(previous){const result=await env.DB.prepare('UPDATE documents SET title=?,data=?,version=?,updated_at=? WHERE id=? AND owner_id=? AND version=?').bind(v.title,data,next,now,v.id,user.id,v.version).run();if(!result.meta.changes)return json({error:'A newer version exists. Reload before saving.'},409)}else{const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM documents WHERE owner_id=?').bind(user.id).first<{n:number}>();if((count?.n||0)>=100)return json({error:'Your library is full. Export and delete an older document first.'},400);await env.DB.prepare('INSERT INTO documents (id,owner_id,kind,title,data,version,updated_at) VALUES (?,?,?,?,?,?,?)').bind(v.id,user.id,v.kind,v.title,data,next,now).run()}return json({version:next,updated_at:now})}
if(path.startsWith('/api/documents/')&&method==='DELETE'){await env.DB.prepare('DELETE FROM documents WHERE id=? AND owner_id=?').bind(path.split('/').pop(),user.id).run();return json({ok:true})}
if(path==='/api/progress'&&method==='GET'){const rows=await env.DB.prepare('SELECT lesson_id FROM progress WHERE owner_id=?').bind(user.id).all<{lesson_id:string}>();return json(rows.results.map(x=>x.lesson_id))}
if(path==='/api/progress'&&method==='POST'){const v=z.object({lessonId:str(80),answer:z.number().int()}).parse(await body(request));const lesson=LESSONS.find(x=>x.id===v.lessonId);if(!lesson)return json({error:'Lesson not found.'},404);if(v.answer!==lesson.correct)return json({error:lesson.explanation},400);await env.DB.prepare('INSERT INTO progress (owner_id,lesson_id,completed_at) VALUES (?,?,?) ON CONFLICT(owner_id,lesson_id) DO NOTHING').bind(user.id,v.lessonId,new Date().toISOString()).run();return json({ok:true})}
if(path==='/api/submissions'&&method==='GET'){const rows=await env.DB.prepare('SELECT * FROM submissions WHERE owner_id=? ORDER BY created_at DESC LIMIT 100').bind(user.id).all();return json(rows.results)}
if(path==='/api/submissions'&&method==='POST'){const v=submissionSchema.parse(await body(request));const count=await env.DB.prepare("SELECT COUNT(*) AS n FROM submissions WHERE owner_id=? AND status='pending'").bind(user.id).first<{n:number}>();if((count?.n||0)>=10)return json({error:'You have ten resources awaiting review. Please wait for those to be reviewed.'},429);const profile=await env.DB.prepare('SELECT name FROM profiles WHERE id=?').bind(user.id).first<{name:string}>();const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO submissions (id,owner_id,author,title,format,kind,description,url,body,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,user.id,profile?.name||'SKB contributor',v.title,v.format,v.kind,v.description,v.url,v.body,'pending',new Date().toISOString()).run();return json({id,status:'pending'},201)}
if(path==='/api/reports'&&method==='POST'){const v=z.object({resourceId:str(100),reason:str(1000)}).parse(await body(request));const exists=await env.DB.prepare("SELECT id FROM submissions WHERE id=? AND status='approved'").bind(v.resourceId).first();if(!exists)return json({error:'Resource not found.'},404);const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM reports WHERE owner_id=? AND created_at>?').bind(user.id,new Date(Date.now()-86400000).toISOString()).first<{n:number}>();if((count?.n||0)>=10)return json({error:'Daily report limit reached.'},429);await env.DB.prepare('INSERT INTO reports (id,resource_id,owner_id,reason,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),v.resourceId,user.id,v.reason,new Date().toISOString()).run();return json({ok:true})}
if(path.startsWith('/api/admin')){if(!user.admin)return json({error:'Only the site editor can moderate resources.'},403);if(path==='/api/admin'&&method==='GET'){const [submissions,reports]=await Promise.all([env.DB.prepare('SELECT * FROM submissions ORDER BY created_at DESC LIMIT 200').all(),env.DB.prepare('SELECT * FROM reports ORDER BY created_at DESC LIMIT 100').all()]);return json({submissions:submissions.results,reports:reports.results})}if(path==='/api/admin/review'&&method==='POST'){const v=z.object({id:z.string().uuid(),status:z.enum(['approved','rejected','pending'])}).parse(await body(request));await env.DB.prepare('UPDATE submissions SET status=? WHERE id=?').bind(v.status,v.id).run();return json({ok:true})}}
return json({error:'Not found.'},404)}
export default {async fetch(request:Request,env:Env):Promise<Response>{try{if(new URL(request.url).pathname.startsWith('/api/'))return await api(request,env);const response=await env.ASSETS.fetch(request);const headers=new Headers(response.headers);headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','strict-origin-when-cross-origin');headers.set('Permissions-Policy','camera=(), microphone=(self)');return new Response(response.body,{status:response.status,headers})}catch(e){if(e instanceof z.ZodError)return json({error:e.issues[0]?.message||'Check the form values.'},400);if(e instanceof SyntaxError)return json({error:'Invalid JSON.'},400);console.error('Request failed',e instanceof Error?e.message:'Unknown error');return json({error:'We could not save or load this right now. Your draft is still on screen; please try again.'},503)}}};
