export type Slide={title:string;points:string[];narration:string};
export type Lesson={id:string;title:string;format:string;level:string;minutes:number;description:string;exercise:string;question:string;answers:string[];correct:number;explanation:string;slides:Slide[]};
export const LESSONS:Lesson[]=[
{id:'build-an-argument',title:'Make an argument that holds up',format:'All formats',level:'Start here',minutes:1,description:'Turn an opinion into a claim, a reason, and a consequence your audience can follow.',exercise:'Choose an issue you care about. Write one claim, a two-step causal explanation, and an impact. Mark exactly where you need a source.',question:'What does a warrant explain?',answers:['Why the claim is true','How loudly to speak','Which team speaks first'],correct:0,explanation:'A warrant connects your evidence and reasoning to the claim. A source alone does not explain the connection.',slides:[
{title:'An opinion is a starting point',points:['Claim: what you want us to believe','Warrant: why it is true','Impact: why it matters'],narration:'A persuasive argument has three connected parts. The claim tells your audience what to believe. The warrant explains why that claim follows. The impact tells us why the issue matters. If you skip the warrant, you ask the audience to supply your reasoning for you.'},
{title:'Show the causal steps',points:['Policy or action','Change in behavior','Consequence for people'],narration:'Suppose your claim is that a later school start improves learning. Do not jump straight from the policy to better grades. Explain how a later start could change sleep, how sleep could affect attention, and what evidence tests each link. This is an example to research, not a verified factual claim.'},
{title:'Evidence supports a specific link',points:['Read the original source','Preserve context and limitations','Explain what the source proves'],narration:'A statistic is useful only when it supports the step you are defending. Record the author, date, title, and link. Check whether the source establishes causation or only a relationship. End by explaining the consequence and why it deserves weight. Now build one argument of your own.'}]},
{id:'pf-round',title:'Your first Public Forum round',format:'Public Forum',level:'Beginner',minutes:1,description:'Understand who speaks, how crossfire works, and what each speech needs to accomplish.',exercise:'Open the practice room with a partner. Complete one constructive and crossfire, then swap roles.',question:'What should final focus do?',answers:['Introduce an unrelated new contention','Resolve the decisive comparison already developed','Repeat every word of the constructive'],correct:1,explanation:'Final focus should explain the winning comparison using the arguments developed through the round.',slides:[
{title:'Two teams. One resolution.',points:['PRO supports the resolution','CON opposes the resolution','Side and speaking order are separate'],narration:'Public Forum is a two versus two debate. One team supports the resolution and the other opposes it. Speaking first does not automatically mean being pro. The coin flip process determines choices about side or speaking order. Confirm the tournament rules before a competition.'},
{title:'Build, clash, narrow, decide',points:['Constructive and rebuttal: 4 minutes','Summary: 3 minutes','Final focus: 2 minutes'],narration:'The standard practice sequence starts with four minute constructives, followed by crossfire. Second speakers give four minute rebuttals and another crossfire. First speakers give three minute summaries. After grand crossfire, second speakers deliver two minute final focuses. Each crossfire lasts three minutes. This app starts with three minutes of preparation per team.'},
{title:'Every speech has a job',points:['Crossfire tests a claim','Summary narrows the debate','Final focus gives a reason to decide'],narration:'Use crossfire to ask short questions and listen to the answer. In summary, choose the arguments that still matter and explain their impacts. In final focus, tell the judge why your comparison wins. Do not rely on a concession unless you explain its importance in a speech. Try the complete sequence in the practice room.'}]},
{id:'rebuttal',title:'Respond to the argument they made',format:'Debate',level:'Intermediate',minutes:1,description:'Practice clear clash, line-by-line responses, and meaningful impact comparison.',exercise:'Take one opposing contention. Write its strongest version, then attack a specific link and explain the consequence.',question:'Which response creates the clearest clash?',answers:['Their argument is bad','They never prove the link from their policy to the claimed outcome','Our team worked harder'],correct:1,explanation:'A specific response identifies the contested step and gives the judge a reason to change its weight.',slides:[
{title:'Locate the disagreement',points:['What is their actual claim?','Which link is contested?','What follows if you are right?'],narration:'A rebuttal is more than a second constructive. First identify the argument you are answering. Restate it fairly, then locate the disagreement. You might contest the evidence, the causal link, the size of an impact, or the comparison between competing harms.'},
{title:'Signpost, answer, explain',points:['On their first contention…','The mechanism fails because…','That means the impact deserves less weight…'],narration:'Use a simple pattern: signpost, answer, explain. On their first contention, identify the mechanism they need. Give a reason it may not hold. Then explain why that reduces the impact. A label such as no link is not a complete answer until you explain the missing connection.'},
{title:'Compare rather than list',points:['Magnitude: how large?','Probability: how likely?','Timeframe and reversibility'],narration:'Two teams can both identify real harms. The judge still needs a comparison. Consider magnitude, probability, timeframe, and reversibility. Explain why the dimension you choose matters in this debate. Do not merely list those words. Use them to resolve the specific clash on the flow.'}]},
{id:'judge-a-round',title:'Give a ballot that teaches',format:'Judging',level:'All levels',minutes:1,description:'Separate your personal opinion from the round and give feedback debaters can act on.',exercise:'Watch or practice a round. Write a reason for decision that names the decisive clash, both responses, and your comparison.',question:'A useful reason for decision should be based on…',answers:['The position you personally prefer','The arguments and responses presented in the round','Which school you recognize'],correct:1,explanation:'Evaluate the debate the students presented. Explain the decisive comparison, then offer separate coaching feedback.',slides:[
{title:'Judge the debate in front of you',points:['Flow both sides fairly','Track responses and extensions','Separate your knowledge from the record'],narration:'Judging asks you to evaluate the debate in front of you. Write down claims and responses on both sides. Avoid adding an argument a team never made simply because you know it. Your personal view of the resolution is different from your decision about who won this round.'},
{title:'Explain the decisive comparison',points:['Name the central clash','Describe each team’s response','Explain which response carried the decision'],narration:'A useful ballot names the central clash, explains how each team handled it, and gives a reason one comparison prevailed. Saying one team was more persuasive gives very little information. Instead describe the argument that survived and why it outweighed the remaining offense.'},
{title:'Feedback should be actionable',points:['One specific strength','One next practice task','Respectful, behavior-based language'],narration:'After the decision, give one specific strength and one next step. For example: your signposting made the rebuttal easy to follow; next time, spend thirty seconds explaining why your impact is more likely. Keep feedback about observable choices. Speaker points follow the tournament rubric and are separate from personal approval.'}]},
{id:'speech-delivery',title:'Sound clear, not rehearsed',format:'Speech',level:'Beginner',minutes:1,description:'Use pace, pauses, and emphasis to help listeners understand your ideas.',exercise:'Record a sixty-second explanation. Listen once for clarity and once for structure. Re-record with two deliberate pauses.',question:'When should you pause deliberately?',answers:['After a key idea so listeners can process it','Never','Only when you forget everything'],correct:0,explanation:'Pauses can clarify structure, emphasize meaning, and make a speech easier to follow.',slides:[
{title:'Clarity is a listener’s experience',points:['One idea per sentence','Explain unfamiliar terms','Make the structure audible'],narration:'Clear speaking is not simply speaking slowly. It means making your ideas easy to follow. Use one main idea per sentence, define unfamiliar terms, and tell your listener where you are going. A strong opening gives both a reason to care and a map of the speech.'},
{title:'Give your important words space',points:['Pause after a key claim','Vary emphasis naturally','Use a sustainable pace'],narration:'A pause gives an important idea room to land. Vary your emphasis to reflect meaning rather than repeating the same pattern. Your ideal pace depends on the audience and task. A word count estimate is only a planning aid, not a score for speaking quality.'},
{title:'Practice one change at a time',points:['Record a short attempt','Choose one improvement','Repeat and compare'],narration:'Record a short explanation and listen back. Choose one improvement: a clearer opening, fewer fillers, or a pause after your main claim. Repeat the same passage and compare. This makes improvement observable. The practice room lets you record and download a take without publishing it.'}]},
{id:'impromptu',title:'Build a speech under time pressure',format:'Impromptu',level:'Beginner',minutes:1,description:'Turn an unfamiliar prompt into a coherent short speech with a clear takeaway.',exercise:'Choose an everyday object. Take one minute to prepare a two-minute speech about a lesson it represents.',question:'What is the most useful first step in short prep?',answers:['Write every sentence','Choose a clear central message','Find the longest possible quotation'],correct:1,explanation:'A central message helps you choose examples and keeps a short speech coherent.',slides:[
{title:'Choose your message first',points:['What does the prompt suggest?','What do you want listeners to remember?','State it in one sentence'],narration:'In impromptu speaking, the hardest part is often choosing. Read the prompt, decide what it suggests, and write a one sentence message. You do not need the most unusual interpretation. You need an interpretation you can explain with clarity and purpose.'},
{title:'Use a simple structure',points:['Opening and central idea','Two examples with explanation','A conclusion that returns to the idea'],narration:'Use a structure you can remember. Open with your central idea, develop two examples, and return to the idea at the end. Explain how each example supports the message. An anecdote without analysis is a story, but not yet a persuasive point.'},
{title:'Adapt to the event',points:['Check the tournament’s prep rules','Respect the time limit','Reflect on structure after the speech'],narration:'Impromptu rules vary across leagues and tournaments. Check the preparation and speaking limits before you compete. In practice, use one minute to prepare and two minutes to speak. Afterwards, ask whether a listener could summarize your message and describe how your examples supported it.'}]}
];
