export const FORMATS=['All formats','Public Forum','Debate','Speech','Judging','Impromptu','Extemporaneous','Original Oratory','Model UN','British Parliamentary','Congressional','Mock Trial'];
export const RESOURCES=[
{id:'pf-flow',title:'Public Forum flow sheet',format:'Public Forum',kind:'Template',description:'A column for every speech, with space to track responses and impact comparisons.',body:'Use one row for each contention. Track the claim, response, extension, and final comparison.\n\nColumns: First constructive | Second constructive | First rebuttal | Second rebuttal | First summary | Second summary | First final focus | Second final focus.\n\nMark unanswered arguments, but still evaluate whether the team explained why they matter. Crossfire concessions should be brought into a speech. Download your practice round to keep a complete flow and ballot.',url:''},
{id:'evidence-check',title:'Before you read a card',format:'All formats',kind:'Checklist',description:'A practical evidence integrity checklist for competitors and teachers.',body:'1. Open the original source, not only a search snippet.\n2. Record author, publication, date, title, and URL.\n3. Keep the quotation accurate and preserve context.\n4. Separate the author’s words from your interpretation.\n5. Check whether the method supports your specific claim.\n6. Disclose limits, uncertainty, and contrary findings.\n7. Be able to provide the source if asked.\n\nAI output is not a source. Verify every cited claim before competition.',url:''},
{id:'ballot-guide',title:'A ballot students can learn from',format:'Judging',kind:'Guide',description:'Turn a decision into useful feedback with a transparent reason for decision.',body:'Decision: Which side wins the debate as presented?\n\nDecisive clash: Name the issue that determined your decision.\n\nComparison: Explain both teams’ arguments and why one response or impact carried more weight.\n\nStrength: Name an observable behavior to repeat.\n\nNext step: Give one concrete practice task.\n\nKeep speaker points within the tournament’s rubric. Do not use accent, identity, or disagreement with a position as a substitute for evaluating the speech.',url:''},
{id:'lesson-plan',title:'Run a 45-minute club session',format:'All formats',kind:'Teaching plan',description:'A repeatable teach–practice–reflect session for a small group.',body:'0–5 minutes: Ask students to give a one-sentence position on a familiar issue.\n5–12: Teach claim, warrant, and impact with one worked example.\n12–22: Pairs build opposing arguments and identify sources they would need.\n22–32: Run a constructive and crossfire using the practice room.\n32–40: Students exchange one strength and one specific next step.\n40–45: Re-deliver the weakest section and record a takeaway.\n\nRotate speakers and judges so every learner practices listening as well as advocacy.',url:''},
{id:'extemp-plan',title:'Extemporaneous speaking prep map',format:'Extemporaneous',kind:'Template',description:'Structure a researched response without losing the question.',body:'Question: Write the exact question.\nAnswer: State your thesis directly.\nPoint one: Claim, source, explanation.\nPoint two: Claim, source, explanation.\nPoint three: Claim, source, explanation.\nConclusion: Return to the question and explain what your answer means.\n\nVerify the event’s preparation time, speech limit, source rules, and permitted materials. Maintain a source log and distinguish reporting from opinion.',url:''},
{id:'oratory',title:'Original Oratory planning canvas',format:'Original Oratory',kind:'Template',description:'Build an original message around an audience, a problem, and a meaningful response.',body:'Audience: Who needs to hear this?\nProblem: What misunderstanding or behavior do you want to address?\nThesis: What should the audience think or do differently?\nStory: What experience illustrates the issue without pretending to prove everything?\nEvidence: Which verified sources support your broader claims?\nResponse: What realistic change do you propose?\nClosing: Return to your central image or idea.\n\nCheck your league’s rules on length, originality, quotation, and assistance.',url:''},
{id:'nsda',title:'NSDA rules and learning resources',format:'All formats',kind:'Official resource',description:'Consult the National Speech & Debate Association for current event rules and resources.',body:'Use the association’s current manuals and tournament guidance as the authority for event-specific rules. Local tournaments may adopt variations.',url:'https://www.speechanddebate.org/resources/'},
{id:'idebate',title:'International Debate Education Association',format:'Debate',kind:'External resource',description:'Explore international debate education and community initiatives.',body:'An external starting point for debate education. SKB is not affiliated with this organization.',url:'https://idebate.net/'},
{id:'mun',title:'Model UN position-paper outline',format:'Model UN',kind:'Template',description:'Connect country policy, committee mandate, and workable proposals.',body:'Country and committee: Identify your assigned delegation and mandate.\nBackground: Summarize the issue using verified sources.\nCountry position: Explain documented policy and interests.\nPast action: Identify relevant agreements, resolutions, and national measures.\nProposals: Offer measures your committee can actually pursue.\n\nDistinguish the position you represent from your personal views. Follow the conference’s format and source requirements.',url:''},
{id:'bp',title:'British Parliamentary role checklist',format:'British Parliamentary',kind:'Guide',description:'A starting checklist for opening and closing teams in a four-team debate.',body:'Opening Government: Establish a clear interpretation and positive case.\nOpening Opposition: Engage that case and develop opposition.\nClosing Government: Add a distinct, relevant contribution.\nClosing Opposition: Add a distinct opposition contribution.\nWhip speeches: Compare the important contributions and explain the ranking.\n\nConsult the tournament briefing for speech time, points of information, and adjudication standards. PF timings do not apply to BP.',url:''}
];
