export type Team='PRO'|'CON';
export type Stage={name:string;seconds:number;speaker:1|2|0;slot:'first'|'second'|'both';focus:string};
export const STAGES:Stage[]=[
{name:'Constructive',seconds:240,speaker:1,slot:'first',focus:'Define the resolution, explain your framework, and build warranted contentions with sourced evidence.'},
{name:'Constructive',seconds:240,speaker:1,slot:'second',focus:'Present an independent case. Make your position and impacts clear to a first-time listener.'},
{name:'Crossfire',seconds:180,speaker:1,slot:'both',focus:'The first speaker asks the first question. Ask a short question, listen, and follow up.'},
{name:'Rebuttal',seconds:240,speaker:2,slot:'first',focus:'Answer the other case line by line. Explain which link, warrant, or impact fails.'},
{name:'Rebuttal',seconds:240,speaker:2,slot:'second',focus:'Respond to the first rebuttal and address the opposing case. Signpost each answer.'},
{name:'Crossfire',seconds:180,speaker:2,slot:'both',focus:'Second speakers test each other’s responses. Seek a useful concession rather than a speech.'},
{name:'Summary',seconds:180,speaker:1,slot:'first',focus:'Narrow to the strongest offense, answer essential defense, and compare impacts.'},
{name:'Summary',seconds:180,speaker:1,slot:'second',focus:'Extend the arguments you need to win and explain why they outweigh the other side.'},
{name:'Grand crossfire',seconds:180,speaker:0,slot:'both',focus:'All four debaters participate. Clarify the remaining clash and give everyone space.'},
{name:'Final focus',seconds:120,speaker:2,slot:'first',focus:'Give the judge a clear reason for decision using arguments carried through summary.'},
{name:'Final focus',seconds:120,speaker:2,slot:'second',focus:'Resolve the decisive comparison. Explain why your remaining offense wins the ballot.'}
];
export function stageTeam(stage:Stage,first:Team):Team|'BOTH'{return stage.slot==='both'?'BOTH':stage.slot==='first'?first:first==='PRO'?'CON':'PRO'}
export function elapsedRemaining(deadline:number,now:number){return Math.max(0,Math.ceil((deadline-now)/1000))}
export function clock(seconds:number){return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}
export type Round={id:string;title:string;resolution:string;scenario:string;side:Team;first:Team;mode:'guided'|'partner';stage:number;remaining:number;prep:Record<Team,number>;notes:Record<string,string>;transcripts:Record<string,string>;complete:boolean;ballot:{winner:Team|'';reason:string;strength:string;nextStep:string;points:string};createdAt:string};
export function newRound(input:Pick<Round,'resolution'|'scenario'|'side'|'first'|'mode'>):Round{return {id:crypto.randomUUID(),title:input.resolution,...input,stage:0,remaining:240,prep:{PRO:180,CON:180},notes:{},transcripts:{},complete:false,ballot:{winner:'',reason:'',strength:'',nextStep:'',points:''},createdAt:new Date().toISOString()}}
export const SCENARIOS=[
{id:'phones',resolution:'Resolved: Schools should restrict smartphone use during the school day.',pro:{claim:'A school-day restriction protects focused learning.',warrant:'Notifications and easy access create opportunities for distraction. A shared rule changes the learning environment for everyone.',impact:'Compare the learning time protected across a whole school against the costs of a restriction.',answer:'Exceptions for accessibility and emergencies can be built into the policy. Explain whether those exceptions preserve the main benefit.'},con:{claim:'A blanket restriction sacrifices useful access and student autonomy.',warrant:'Students use devices for accessibility, coordination, and learning. Teaching responsible use may address distraction with fewer restrictions.',impact:'Compare the chance of better attention with the consequences for students who need access.',answer:'A device rule alone does not establish improved learning. Ask whether enforcement, school devices, and non-phone distractions undermine the mechanism.'}},
{id:'transit',resolution:'Resolved: Cities should make public transit fare-free.',pro:{claim:'Removing fares can make essential travel more accessible.',warrant:'The fare is a direct barrier for some riders. Removing that barrier makes more trips affordable without requiring individual eligibility checks.',impact:'Weigh access to work, school, and services against the opportunity cost of funding the policy.',answer:'Compare the marginal value of fare relief with service investment. The policy needs a funding mechanism, not an assumption that transit is costless.'},con:{claim:'Reliable service deserves priority over eliminating fares.',warrant:'When the budget is limited, resources spent replacing fare revenue cannot also expand routes or frequency.',impact:'Compare a cheaper trip that rarely arrives with a reliable network that reaches more people.',answer:'Targeted fare support could protect affordability while preserving resources for service. Test whether the affirmative addresses this tradeoff.'}},
{id:'ai',resolution:'Resolved: Schools should permit generative AI in classroom assignments.',pro:{claim:'Supervised AI use can support feedback and learning.',warrant:'With disclosure and teacher guidance, students can critique drafts, compare explanations, and learn to verify automated claims.',impact:'Weigh access to iterative feedback and AI literacy against risks to independent thinking.',answer:'Permission can include boundaries: students must show their reasoning and disclose assistance. Test whether a ban teaches responsible use.'},con:{claim:'Routine AI assistance can weaken independent skill development.',warrant:'If students outsource the difficult part of reasoning, a polished product can conceal a weaker learning process.',impact:'Compare short-term output improvements against durable writing, research, and judgment skills.',answer:'Disclosure does not prove learning occurred. Ask what assessment actually measures the student’s own understanding.'}}
];
export function opponentPrompt(round:Round){const s=SCENARIOS.find(x=>x.id===round.scenario);if(!s)return 'Custom resolution: invite a partner or enter an opposing case. Guided content is available for the three practice topics.';const side=round.side==='PRO'?'con':'pro';const a=s[side],st=STAGES[round.stage];if(st.slot==='both')return `Practice questions to answer aloud:\n\n1. What is the precise mechanism behind your strongest claim?\n2. What source supports that mechanism, and what does it actually establish?\n3. Why does your impact outweigh ${side==='pro'?'the cost of restricting individual choices':'the potential benefit of the policy'}?\n4. What would change your conclusion?`;if(st.name==='Constructive')return `${a.claim}\n\n${a.warrant}\n\n${a.impact}\n\nResearch task: find and verify a source before treating this practice argument as evidence.`;if(st.name==='Rebuttal')return `${a.answer}\n\nCompare this response to the specific argument on your flow. Practice explaining what the response contests and whether it answers your actual claim.`;if(st.name==='Summary')return `${a.claim}\n\nExtend the mechanism: ${a.warrant}\n\nWeigh the remaining clash: ${a.impact}`;return `The decisive question is whether our mechanism survives the responses. ${a.claim}\n\n${a.impact}\n\nPractice your own final comparison using only arguments already developed in this round.`}
