import {chromium} from '/opt/codex/runtimes/cua/lib/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
await page.addInitScript(()=>{document.modelContext={registerTool(tool){window.skbTools=window.skbTools||{};window.skbTools[tool.name]=tool;}}});
await page.goto('http://127.0.0.1:8787/',{waitUntil:'networkidle'});
assert.equal(await page.evaluate(()=>window.skbTools.get_free_lesson_catalog.execute({}).length),6);
assert.equal(await page.evaluate(async()=>{try{await window.skbTools.open_free_lesson.execute({lessonId:'missing'});return false}catch{return true}}),true);
await page.screenshot({path:'/workspace/scratch/skb-desktop.png',fullPage:true});
await page.getByRole('link',{name:'Practice room',exact:true}).click();
await page.getByLabel('Your side').selectOption('CON');
await page.getByLabel('Speaking first').selectOption('CON');
await page.getByRole('button',{name:'Enter practice room'}).click();
await page.getByRole('button',{name:'Start timer',exact:true}).click();await page.waitForTimeout(1200);
assert.notEqual(await page.locator('.timer').textContent(),'4:00');
await page.getByRole('button',{name:'Pause',exact:true}).click();
await page.getByRole('button',{name:/PRO prep/}).click();await page.waitForTimeout(1100);
assert.notEqual(await page.locator('.timer').textContent(),'3:00');
await page.getByRole('button',{name:/PRO prep.*End prep/}).click();
await page.getByLabel('Track claims, responses, and comparisons').fill('PRO: attention benefit. CON: access and autonomy. Compare alternatives.');
await page.getByRole('button',{name:'Save',exact:true}).click();
await page.getByText('Round saved to your library.',{exact:true}).waitFor();
await page.screenshot({path:'/workspace/scratch/skb-practice.png',fullPage:true});
for(let i=0;i<10;i++)await page.getByRole('button',{name:'Next segment',exact:true}).click();
await page.getByRole('button',{name:'Finish round'}).click();
await page.getByRole('combobox',{name:/^Decision/}).selectOption('CON');
await page.getByLabel('Reason for decision',{exact:true}).fill('CON answered the mechanism and compared an alternative.');
await page.getByRole('button',{name:'Save round & ballot'}).click();
await page.getByRole('link',{name:'Case workshop',exact:true}).click();
await page.getByLabel('Case title',{exact:true}).fill('QA restored case');
await page.getByLabel('Resolution',{exact:true}).fill('Resolved: Schools should restrict smartphone use during the school day.');
await page.getByLabel('Framework',{exact:true}).fill('Compare student learning and access.');
await page.getByLabel('Claim',{exact:true}).first().fill('A clear rule can protect focused learning.');
await page.getByRole('button',{name:'Save case',exact:true}).click();await page.getByText('Case saved to your library.').waitFor();
await page.getByRole('link',{name:'Video lessons',exact:false}).first().click();
await page.locator('.lesson-card').first().click();
await page.locator('video').waitFor();await page.waitForFunction(()=>document.querySelector('video').readyState>=1);
assert.ok(await page.locator('video').evaluate(v=>v.duration>40));
await page.locator('video').evaluate(v=>{v.muted=true;return v.play()});await page.waitForTimeout(700);assert.ok(await page.locator('video').evaluate(v=>v.currentTime>0));await page.locator('video').evaluate(v=>v.pause());
await page.getByLabel('Why the claim is true',{exact:true}).check();
await page.getByRole('button',{name:/Check (& mark complete|again)/}).click();await page.getByText('Lesson complete. Put it into practice next.').waitFor();
await page.getByRole('link',{name:'Resource library',exact:true}).click();
await page.getByLabel('Search resources').fill('evidence');await page.locator('.resource-card').first().click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Close resource'}).click();
await page.getByRole('link',{name:'Contribute',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('QA lesson guide');await page.getByLabel('What will someone learn?').fill('Students learn to identify a causal link.');await page.getByLabel('Resource content').fill('This is an original practice guide: write one claim, identify the mechanism, and compare competing impacts.');await page.getByLabel(/I created this content/).check();await page.getByRole('button',{name:'Submit for review'}).click();await page.getByText(/Your resource is in the review queue/).waitFor();
await page.getByRole('link',{name:'Editor studio',exact:true}).click();await page.getByRole('button',{name:'Approve',exact:true}).first().click();await page.getByText('Review saved.').waitFor();
await page.getByRole('link',{name:'My work',exact:true}).click();await page.getByText('QA restored case',{exact:true}).first().waitFor();
assert.ok((await page.locator('.work-row').count())>=2);
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8787/#/home',{waitUntil:'networkidle'});await page.screenshot({path:'/workspace/scratch/skb-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await page.getByRole('button',{name:'Toggle navigation'}).click();await page.getByRole('link',{name:'Practice room',exact:true}).click();await page.getByRole('button',{name:'Set up another round'}).click();await page.getByRole('button',{name:'Enter practice room'}).click();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
assert.deepEqual(errors,[]);
assert.equal(await page.evaluate(async()=>(await window.skbTools.open_free_lesson.execute({lessonId:'judge-a-round'})).lessonId),'judge-a-round');
await page.getByRole('heading',{name:'Give a ballot that teaches',exact:true}).waitFor();
console.log('PASS: round timing, prep, all 11 segments, cloud save, case editing, video playback, quiz progress, resources, submission/review, history, mobile layout.');
await browser.close();
